"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";

type CertificationInput={title:string;issuer:string;description:string;type:string;sortOrder:string;isPublished:boolean};

async function requireAdmin(){const supabase=await createClient();const {data:claimsData}=await supabase.auth.getClaims();const userId=claimsData?.claims?.sub;if(!userId)throw new Error("You must be signed in as an admin.");const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",userId).maybeSingle();if(!admin)throw new Error("Admin access is required.");return supabase;}
function parseOrder(value:string,fallback=1){const parsed=Number.parseInt(value,10);return Number.isFinite(parsed)?parsed:fallback;}
async function getOrders(supabase:Awaited<ReturnType<typeof createClient>>){const {data,error}=await supabase.from("certifications").select("id, sort_order").order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(error)throw new Error(error.message);return data??[];}
async function setOrders(supabase:Awaited<ReturnType<typeof createClient>>,ids:string[],start:number){for(let i=0;i<ids.length;i++){const {error}=await supabase.from("certifications").update({sort_order:start+i}).eq("id",ids[i]);if(error)throw new Error(error.message);}}
function payload(input:CertificationInput,sortOrder:number){return{title:input.title.trim(),issuer:input.issuer.trim(),description:input.description.trim(),type:input.type.trim()==="virtual"?"virtual":"formal",sort_order:sortOrder,is_published:input.isPublished};}
function validate(input:CertificationInput){if(!input.title.trim())throw new Error("Title is required.");if(!input.issuer.trim())throw new Error("Issuer or platform is required.");}
export async function createCertification(input:CertificationInput){validate(input);const supabase=await requireAdmin();const existing=await getOrders(supabase);const target=Math.max(1,Math.min(parseOrder(input.sortOrder,existing.length+1),existing.length+1));const affected=existing.filter(x=>x.sort_order>=target).sort((a,b)=>a.sort_order-b.sort_order);await setOrders(supabase,affected.map(x=>x.id),target+1);const {error}=await supabase.from("certifications").insert(payload(input,target));if(error)throw new Error(error.message);revalidatePath("/admin/certifications");revalidatePath("/admin");}
export async function updateCertification(id:string,input:CertificationInput){validate(input);const supabase=await requireAdmin();const existing=await getOrders(supabase);const current=existing.find(x=>x.id===id);if(!current)throw new Error("Credential record not found.");const target=Math.max(1,Math.min(parseOrder(input.sortOrder,current.sort_order),existing.length));const affected=existing.filter(x=>x.id!==id&&x.sort_order>=Math.min(current.sort_order,target)&&x.sort_order<=Math.max(current.sort_order,target)).sort((a,b)=>a.sort_order-b.sort_order);if(target<current.sort_order)await setOrders(supabase,affected.map(x=>x.id),target+1);if(target>current.sort_order)await setOrders(supabase,affected.map(x=>x.id),current.sort_order);const {error}=await supabase.from("certifications").update(payload(input,target)).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/certifications");revalidatePath("/admin");}
export async function deleteCertification(id:string){const supabase=await requireAdmin();const existing=await getOrders(supabase);const current=existing.find(x=>x.id===id);if(!current)throw new Error("Credential record not found.");const {error}=await supabase.from("certifications").delete().eq("id",id);if(error)throw new Error(error.message);const affected=existing.filter(x=>x.id!==id&&x.sort_order>current.sort_order).sort((a,b)=>a.sort_order-b.sort_order);await setOrders(supabase,affected.map(x=>x.id),current.sort_order);revalidatePath("/admin/certifications");revalidatePath("/admin");}
export async function toggleCertificationPublished(id:string,isPublished:boolean){const supabase=await requireAdmin();if(!id)throw new Error("Credential ID is required.");const {error}=await supabase.from("certifications").update({is_published:isPublished}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/certifications");revalidatePath("/admin");}
