"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";

type SkillGroupInput={title:string;skills:string;sortOrder:string;isPublished:boolean};
type LearningAreaInput={title:string;description:string;sortOrder:string;isPublished:boolean};

async function requireAdmin(){const supabase=await createClient();const {data:claimsData}=await supabase.auth.getClaims();const userId=claimsData?.claims?.sub;if(!userId)throw new Error("You must be signed in as an admin.");const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",userId).maybeSingle();if(!admin)throw new Error("Admin access is required.");return supabase;}
function parseOrder(value:string,fallback=1){const parsed=Number.parseInt(value,10);return Number.isFinite(parsed)?parsed:fallback;}
async function getOrders(supabase:Awaited<ReturnType<typeof createClient>>,table:"skill_groups"|"learning_areas"){const {data,error}=await supabase.from(table).select("id, sort_order").order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(error)throw new Error(error.message);return data??[];}
async function setOrders(supabase:Awaited<ReturnType<typeof createClient>>,table:"skill_groups"|"learning_areas",ids:string[],start:number){for(let i=0;i<ids.length;i++){const {error}=await supabase.from(table).update({sort_order:start+i}).eq("id",ids[i]);if(error)throw new Error(error.message);}}
function skillPayload(input:SkillGroupInput,sortOrder:number){return{title:input.title.trim(),skills:input.skills.split(",").map(item=>item.trim()).filter(Boolean),sort_order:sortOrder,is_published:input.isPublished};}
function learningPayload(input:LearningAreaInput,sortOrder:number){return{title:input.title.trim(),description:input.description.trim(),sort_order:sortOrder,is_published:input.isPublished};}
function validateTitle(title:string){if(!title.trim())throw new Error("Title is required.");}

export async function createSkillGroup(input:SkillGroupInput){validateTitle(input.title);const supabase=await requireAdmin();const existing=await getOrders(supabase,"skill_groups");const target=Math.max(1,Math.min(parseOrder(input.sortOrder,existing.length+1),existing.length+1));const affected=existing.filter(x=>x.sort_order>=target).sort((a,b)=>b.sort_order-a.sort_order);await setOrders(supabase,"skill_groups",affected.map(x=>x.id),target+1);const {error}=await supabase.from("skill_groups").insert(skillPayload(input,target));if(error)throw new Error(error.message);revalidatePath("/admin/skills");revalidatePath("/admin");}
export async function updateSkillGroup(id:string,input:SkillGroupInput){validateTitle(input.title);const supabase=await requireAdmin();const existing=await getOrders(supabase,"skill_groups");const current=existing.find(x=>x.id===id);if(!current)throw new Error("Skill group not found.");const target=Math.max(1,Math.min(parseOrder(input.sortOrder,current.sort_order),existing.length));const affected=existing.filter(x=>x.id!==id&&x.sort_order>=Math.min(current.sort_order,target)&&x.sort_order<=Math.max(current.sort_order,target)).sort((a,b)=>a.sort_order-b.sort_order);if(target<current.sort_order)await setOrders(supabase,"skill_groups",affected.map(x=>x.id),target+1);if(target>current.sort_order)await setOrders(supabase,"skill_groups",affected.map(x=>x.id),current.sort_order);const {error}=await supabase.from("skill_groups").update(skillPayload(input,target)).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/skills");revalidatePath("/admin");}
export async function deleteSkillGroup(id:string){const supabase=await requireAdmin();const existing=await getOrders(supabase,"skill_groups");const current=existing.find(x=>x.id===id);if(!current)throw new Error("Skill group not found.");const {error}=await supabase.from("skill_groups").delete().eq("id",id);if(error)throw new Error(error.message);const affected=existing.filter(x=>x.id!==id&&x.sort_order>current.sort_order).sort((a,b)=>a.sort_order-b.sort_order);await setOrders(supabase,"skill_groups",affected.map(x=>x.id),current.sort_order);revalidatePath("/admin/skills");revalidatePath("/admin");}
export async function toggleSkillGroupPublished(id:string,isPublished:boolean){const supabase=await requireAdmin();const {error}=await supabase.from("skill_groups").update({is_published:isPublished}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/skills");revalidatePath("/admin");}
export async function createLearningArea(input:LearningAreaInput){validateTitle(input.title);const supabase=await requireAdmin();const existing=await getOrders(supabase,"learning_areas");const target=Math.max(1,Math.min(parseOrder(input.sortOrder,existing.length+1),existing.length+1));const affected=existing.filter(x=>x.sort_order>=target).sort((a,b)=>b.sort_order-a.sort_order);await setOrders(supabase,"learning_areas",affected.map(x=>x.id),target+1);const {error}=await supabase.from("learning_areas").insert(learningPayload(input,target));if(error)throw new Error(error.message);revalidatePath("/admin/skills");revalidatePath("/admin");}
export async function updateLearningArea(id:string,input:LearningAreaInput){validateTitle(input.title);const supabase=await requireAdmin();const existing=await getOrders(supabase,"learning_areas");const current=existing.find(x=>x.id===id);if(!current)throw new Error("Learning area not found.");const target=Math.max(1,Math.min(parseOrder(input.sortOrder,current.sort_order),existing.length));const affected=existing.filter(x=>x.id!==id&&x.sort_order>=Math.min(current.sort_order,target)&&x.sort_order<=Math.max(current.sort_order,target)).sort((a,b)=>a.sort_order-b.sort_order);if(target<current.sort_order)await setOrders(supabase,"learning_areas",affected.map(x=>x.id),target+1);if(target>current.sort_order)await setOrders(supabase,"learning_areas",affected.map(x=>x.id),current.sort_order);const {error}=await supabase.from("learning_areas").update(learningPayload(input,target)).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/skills");revalidatePath("/admin");}
export async function deleteLearningArea(id:string){const supabase=await requireAdmin();const existing=await getOrders(supabase,"learning_areas");const current=existing.find(x=>x.id===id);if(!current)throw new Error("Learning area not found.");const {error}=await supabase.from("learning_areas").delete().eq("id",id);if(error)throw new Error(error.message);const affected=existing.filter(x=>x.id!==id&&x.sort_order>current.sort_order).sort((a,b)=>a.sort_order-b.sort_order);await setOrders(supabase,"learning_areas",affected.map(x=>x.id),current.sort_order);revalidatePath("/admin/skills");revalidatePath("/admin");}
export async function toggleLearningAreaPublished(id:string,isPublished:boolean){const supabase=await requireAdmin();const {error}=await supabase.from("learning_areas").update({is_published:isPublished}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/skills");revalidatePath("/admin");}
